CREATE TABLE teams (
  team_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_name VARCHAR2(80) NOT NULL UNIQUE,
  fifa_code VARCHAR2(3) NOT NULL UNIQUE
);

CREATE TABLE matches (
  match_id NUMBER PRIMARY KEY,
  home_team_id NUMBER NOT NULL REFERENCES teams(team_id),
  away_team_id NUMBER NOT NULL REFERENCES teams(team_id),
  venue VARCHAR2(120) NOT NULL,
  kickoff_label VARCHAR2(120) NOT NULL,
  stage VARCHAR2(80) NOT NULL
);

CREATE TABLE players (
  player_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id NUMBER NOT NULL REFERENCES teams(team_id),
  player_name VARCHAR2(120) NOT NULL,
  position VARCHAR2(40) NOT NULL,
  shirt_number NUMBER NOT NULL
);

CREATE TABLE scouting_reports (
  report_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id NUMBER NOT NULL REFERENCES matches(match_id),
  visibility VARCHAR2(20) NOT NULL,
  report_title VARCHAR2(150) NOT NULL,
  report_text VARCHAR2(1000) NOT NULL,
  access_code VARCHAR2(80) NOT NULL,
  CONSTRAINT chk_report_visibility CHECK (visibility IN ('public', 'internal'))
);

CREATE INDEX idx_players_team ON players(team_id);
CREATE INDEX idx_reports_match ON scouting_reports(match_id);
